### ISSUE TITLE
Please add the feature to register callbacks when long pressed

### ISSUE THREAD

**Issue by PeterHan123** [hideakitai/Debouncer#2]

**Comment by hideakitai** [comment]
Thanks, that's a good idea. I'll try it later in this month.

**Comment by PeterHan123** [comment]
Thanks Hideakitai!

**Comment by hideakitai** [comment]
@PeterHan123 Sorry, you can do it with two `Debouncer`s as is, so I'm going to close this issue. But I've added some new features in v0.2.0.

**Comment by absalom-muc** [comment]
Thank you for this nice library!

You are right that for a long button press a second instance of Debouncer can be used. But then you have to wait "long" time before you can press the button a second time because of the identical rise/fall time. Therefore it would be helpful when rise/fall time could be separated.

**Comment by hideakitai** [comment]
@absalom-muc Thanks, it's a nice suggestion. Could you open another issue about it?
